namespace ReCap.Parser.Catalog;

/// <summary>
/// Noun definition - the main game object type.
/// Size: 480 bytes
/// </summary>
public sealed class NounCatalog : AssetCatalog
{
    protected override void Build()
    {
        Struct("Noun", 480,
            EnumField("nounType", "NounType", 0),
            Bool("clientOnly", 4),
            Bool("isFixed", 5),
            Bool("isSelfPowered", 6),
            EnumField("gfxPickMethod", "GfxPickMethod", 8),
            Float("lifetime", 12),
            Key("prefab", 16),
            Float("graphicsScale", 20),
            Key("modelKey", 36),
            Key("levelEditorModelKey", 52),
            IStruct("bbox", "cSPBoundingBox", 56),
            EnumField("presetExtents", "PresetExtents", 80),
            Key("voice", 96),
            Key("foot", 112),
            Key("flightSound", 128),
            NStruct("gfxStates", "cGameObjectGfxStates", 132),
            NStruct("doorDef", "cDoorDef", 136),
            NStruct("switchDef", "cSwitchDef", 140),
            NStruct("pressureSwitchDef", "cPressureSwitchDef", 144),
            NStruct("crystalDef", "CrystalDef", 148),
            UInt64("assetId", 152),
            Asset("npcClassData", 160),
            Asset("playerClassData", 164),
            Asset("characterAnimationData", 168),
            NStruct("creatureThumbnailData", "cThumbnailCaptureParameters", 172),
            Array("eliteAssetIds", DataType.UInt64, 176, countOffset: 4),
            EnumField("physicsType", "PhysicsType", 184),
            Float("density", 188),
            Key("physicsKey", 204),
            Bool("affectsNavMesh", 208),
            Bool("dynamicWall", 209),
            Asset("aiDefinition", 212),
            Bool("hasNetworkComponent", 216),
            Bool("hasCameraComponent", 217),
            Bool("hasCombatantComponent", 218),
            Bool("hasLocomotion", 219),
            EnumField("locomotionType", "LocomotionType", 220),
            EnumField("spawnTeamId", "spawnTeamId", 224),
            Bool("isIslandMarker", 228),
            CharPtr("activateFnNamespace", 232),
            CharPtr("tickFnNamespace", 236),
            CharPtr("deactivateFnNamespace", 240),
            CharPtr("startFnNamespace", 244),
            CharPtr("endFnNamespace", 248),
            IStruct("componentData", "SharedComponentData", 252),
            NStruct("triggerVolume", "TriggerVolumeDef", 292),
            NStruct("projectile", "ProjectileDef", 296),
            NStruct("orbit", "OrbitDef", 300),
            NStruct("locomotionTuning", "LocomotionTuning", 304),
            Asset("gravityData", 308),
            Key("toonType", 324),
            Bool("isFlora", 328),
            Bool("isMineral", 329),
            Bool("isCreature", 330),
            Bool("isPlayer", 331),
            Bool("isSpawned", 332),
            Key("modelEffect", 348),
            Key("removalEffect", 364),
            Key("meleeDeathEffect", 396),
            Key("meleeCritEffect", 412),
            Key("energyDeathEffect", 428),
            Key("energyCritEffect", 444),
            Key("plasmaDeathEffect", 460),
            Key("plasmaCritEffect", 476)
        );
    }
}
