namespace ReCap.Parser.Catalog;

public sealed class Noun : AssetCatalog
{
    protected override void Build()
    {
        Struct("Noun", 480,
            EnumField("nounType", "NounType", 0),
            Field("clientOnly", DataType.Bool, 4),
            Field("isFixed", DataType.Bool, 5),
            Field("isSelfPowered", DataType.Bool, 6),
            EnumField("gfxPickMethod", "GfxPickMethod", 8),
            Field("lifetime", DataType.Float, 12),
            Field("prefab", DataType.Key, 16),
            Field("graphicsScale", DataType.Float, 20),
            Field("modelKey", DataType.Key, 36),
            Field("levelEditorModelKey", DataType.Key, 52),
            IStruct("bbox", "cSPBoundingBox", 56),
            EnumField("presetExtents", "PresetExtents", 80),
            Field("voice", DataType.Key, 96),
            Field("foot", DataType.Key, 112),
            Field("flightSound", DataType.Key, 128),
            NStruct("gfxStates", "cGameObjectGfxStates", 132),
            NStruct("doorDef", "cDoorDef", 136),
            NStruct("switchDef", "cSwitchDef", 140),
            NStruct("pressureSwitchDef", "cPressureSwitchDef", 144),
            NStruct("crystalDef", "CrystalDef", 148),
            Field("assetId", DataType.UInt64, 152),
            Field("npcClassData", DataType.Asset, 160),
            Field("playerClassData", DataType.Asset, 164),
            Field("characterAnimationData", DataType.Asset, 168),
            NStruct("creatureThumbnailData", "cThumbnailCaptureParameters", 172),
            Array("eliteAssetIds", DataType.UInt64, 176, countOffset: 4),
            EnumField("physicsType", "PhysicsType", 184),
            Field("density", DataType.Float, 188),
            Field("physicsKey", DataType.Key, 204),
            Field("affectsNavMesh", DataType.Bool, 208),
            Field("dynamicWall", DataType.Bool, 209),
            Field("aiDefinition", DataType.Asset, 212),
            Field("hasNetworkComponent", DataType.Bool, 216),
            Field("hasCameraComponent", DataType.Bool, 217),
            Field("hasCombatantComponent", DataType.Bool, 218),
            Field("hasLocomotion", DataType.Bool, 219),
            EnumField("locomotionType", "LocomotionType", 220),
            EnumField("spawnTeamId", "spawnTeamId", 224),
            Field("isIslandMarker", DataType.Bool, 228),
            Field("activateFnNamespace", DataType.CharPtr, 232),
            Field("tickFnNamespace", DataType.CharPtr, 236),
            Field("deactivateFnNamespace", DataType.CharPtr, 240),
            Field("startFnNamespace", DataType.CharPtr, 244),
            Field("endFnNamespace", DataType.CharPtr, 248),
            IStruct("componentData", "SharedComponentData", 252),
            NStruct("triggerVolume", "TriggerVolumeDef", 292),
            NStruct("projectile", "ProjectileDef", 296),
            NStruct("orbit", "OrbitDef", 300),
            NStruct("locomotionTuning", "LocomotionTuning", 304),
            Field("gravityData", DataType.Asset, 308),
            Field("toonType", DataType.Key, 324),
            Field("isFlora", DataType.Bool, 328),
            Field("isMineral", DataType.Bool, 329),
            Field("isCreature", DataType.Bool, 330),
            Field("isPlayer", DataType.Bool, 331),
            Field("isSpawned", DataType.Bool, 332),
            Field("modelEffect", DataType.Key, 348),
            Field("removalEffect", DataType.Key, 364),
            Field("meleeDeathEffect", DataType.Key, 396),
            Field("meleeCritEffect", DataType.Key, 412),
            Field("energyDeathEffect", DataType.Key, 428),
            Field("energyCritEffect", DataType.Key, 444),
            Field("plasmaDeathEffect", DataType.Key, 460),
            Field("plasmaCritEffect", DataType.Key, 476)
        );
    }
}
